name: Testing and Quality

on:
  pull_request:

jobs:
  test:
    runs-on: codeberg-tiny

    container:
      image: node:lts

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run coverage
        run: npm run test:coverage
