name: Release

on:
  workflow_run:
    workflows:
      - Publish Package
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'refs/tags/') == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --exact-match ${{ github.event.workflow_run.head_sha }} 2>/dev/null || true)

          if [ -z "$TAG" ]; then
            echo "No tag found."
            exit 1
          fi

          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.DON_MAGIC_GIRL }}
        run: |
          gh release create "${{ steps.tag.outputs.tag }}" \
            --generate-notes \
            --verify-tag
